### ISSUE TITLE
Invalid Folder Selection

### ISSUE THREAD

**Issue by Gcsaniz** [m-kovalsky/ReportAnalyzer#11]
**Describe the bug**
Unable to open a folder containing a Power BI PBIX and Performance Analyzer file

**To Reproduce**
1. Go to 'File
2. Click on 'Select Folder...''
3. Navigate to the folder containing 1) a .PBIX file and 2) a performance analyzer .json file
4. See error/dialog: "Must select a folder with a Power BI Desktop or Power BI Template file."

**Expected behavior**
Report Analyzer opens and analyses both files.

**Screenshots**
See below.

**Version Number (please complete the following information):**
 - Version 1.6.0
 - Power BI Desktop Version: 2.105.1143.0 64-bit (May 2022)

**Additional context**
![Screen Shot 2022-06-17 at 3 24 04 PM](https://user-images.githubusercontent.com/16419745/174392499-9480a8b1-1f79-4ac0-83bb-587acb6336e3.png)
![Screen Shot 2022-06-17 at 3 51 00 PM](https://user-images.githubusercontent.com/16419745/174392500-f08ab62d-adda-490f-b54c-8e99cfa35be6.png)

**Comment by LuckySelena** [comment]
Hi, has your issue been solved already?

**Comment by Gcsaniz** [comment]
@LuckySelena Have any changes been applied that would fix the issue?

**Comment by LuckySelena** [comment]
> 

No, I met the same issue as you.

**Comment by m-kovalsky** [comment]
Are you still experiencing this in 1.6.3?

**Comment by Gcsaniz** [comment]
@m-kovalsky The issue now appears to be fixed in 1.6.3.

Thanks!
