### ISSUE TITLE
Visual Group items displayed in wrong places

### ISSUE THREAD

**Issue by rudzimj** [m-kovalsky/ReportAnalyzer#13]
**Describe the bug**
It is helpful to group multiple report elements in a group on the Power BI Selection Pane. The Visual Groups are drawn in the correct location by Report Analyzer, but the elements within the group are not.

**To Reproduce**
See Power BI Desktop in attached file: [Sample with Groups.zip](https://github.com/m-kovalsky/ReportAnalyzer/files/9749078/Sample.with.Groups.zip)
1. Created a chart and a text box
2. **View > Selection** to open selection pane
3. Select Text box and chart, right click and **Group**
4. Copy and paste group into second group. Optionally rename and move items.
5. Run Report Analyzer

**Expected behavior**
Each **Text Box** and **Column Chart** should draw on the Report Analyzer screen in the same position as the **Visual Group**.

**Screenshots**
**Report**
<img width="708" alt="image" src="https://user-images.githubusercontent.com/36211641/194948081-351d32a8-a9b8-4d02-9f87-8275318a404e.png">

**Report Analyzer**
<img width="696" alt="image" src="https://user-images.githubusercontent.com/36211641/194948174-7c000092-ba19-49af-8160-64292a44de9d.png">

**Version Number (please complete the following information):**
 - Report Analyzer Version 1.6.0
 - Power BI Desktop September 2022

**Additional context**
It looks like the X and Y coordinates for items in a group are relative coordinates within the group container and not absolute coordinates for the report page:
**ReportObjects_Visuals.txt**
<img width="446" alt="image" src="https://user-images.githubusercontent.com/36211641/194950410-f5a9e26e-c4a5-4b97-a453-4c161bb6d8d2.png">

**Comment by m-kovalsky** [comment]
Resolved in [1.6.2](https://github.com/m-kovalsky/ReportAnalyzer/releases/tag/1.6.2)
