### ISSUE TITLE
Power BI desktop not updating with the latest version

### ISSUE THREAD

**Issue by scramiro** [m-kovalsky/ReportAnalyzer#16]
**Describe the bug**
Even if I reinstall Report Analyzer the External Tool keeps using version 1.6.0 instead of 1.6.2

**Comment by m-kovalsky** [comment]
This shouldn't happen. Please uninstall & reinstall report analyzer.

**Comment by scramiro** [comment]
Hi,

Yes, tried this but didn't fix the problem.

Thanks

**Comment by scramiro** [comment]
Deleting Business Opps external tool fixed this.
