### ISSUE TITLE
1.2 exe not working

### ISSUE THREAD

**Issue by benito2313** [m-kovalsky/ReportAnalyzer#2]
**Describe the bug**
When I try to open the program nothing happens,
When I go back to 1.1 then it works again.

**To Reproduce**
1. Open/start the program or .exe

**Expected behavior**
The program to start.

**Version Number (please complete the following information):**
 - Version 1.2

**Comment by m-kovalsky** [comment]
Try uninstalling and reinstalling (making sure that 1.1 is also uninstalled). Not exactly sure why this is happening in your case.

**Comment by m-kovalsky** [comment]
See version [1.3.0](https://github.com/m-kovalsky/ReportAnalyzer/releases/tag/1.3.0)

**Comment by benito2313** [comment]
Hi, yes the newest version works 👍
Thnx.
