### ISSUE TITLE
Bookmarks and visuals

### ISSUE THREAD

**Issue by benito2313** [m-kovalsky/ReportAnalyzer#3]
**Is your feature request related to a problem? Please describe.**
When I pbix file has bookmarks there are more then one overlapping visuals.
So now I can't see which visuals are when.

**Describe the solution you'd like**
Add the bookmarks in the filter panel or something like that, so you can see which visuals is active when.

**Comment by m-kovalsky** [comment]
This is a good idea. For now, you can toggle to see the hidden visuals but you are correct - if the visuals overlap on the canvas then you may not be able to see all the visuals. As you said, perhaps a filter with the list of bookmarks will do the trick (and clicking on a particular bookmark would show the visuals per the bookmark setting).

**Comment by m-kovalsky** [comment]
This is available as of [1.4.0](https://github.com/m-kovalsky/ReportAnalyzer/releases/tag/1.4.0) . See the 'Bookmarks' slicer.
