### ISSUE TITLE
List unused fields

### ISSUE THREAD

**Issue by DaniilMaslyuk** [m-kovalsky/ReportAnalyzer#5]
**Is your feature request related to a problem? Please describe.**
It's common to have unused fields in the model. Some of them could be so large that removing them would improve the refresh performance, for example.

**Describe the solution you'd like**
It'd be great if the tool listed the unused fields together with the portion of the database size that they occopy. Example: TableA[Column1] is not used in any visual, yet it occupies 14% of the model.

**Describe alternatives you've considered**
If not possible to do as an external tool due to Live Connections, I'd still be happy with a Tabular Editor script that can be executed when connected to a data model (for a list of all fields and a list of fields referenced in the model), with a local PBIX specified for layout parsing (for a list of fields used in visuals).

**Comment by m-kovalsky** [comment]
This is already available in the following script. See the instructions when you download the script. It runs in Tabular Editor. I haven't migrated this portion to the Report Analyzer at it leverages some of Tabular Editor's inherent capabilities (which I would have to reproduce in the Report Analyzer.

https://github.com/m-kovalsky/Tabular#export-report-objects

**Comment by DaniilMaslyuk** [comment]
Thanks, @m-kovalsky -- admittedly, it wasn't obvious to me that there's a relationship between `bool addPersp = false` and ReportObjects_UnusedObjects.txt. Perhaps my feature request can be changed to "try to create ReportObjects_UnusedObjects.txt in case you're connected to a model" or something like that. The file doesn't have the portion of the database size that can be saved by removing a field, but that's all right. Thanks again!

**Comment by m-kovalsky** [comment]
You can collect the portion of the database’s memory which can be saved by running the vertipaq analyzer scripts and adding up the values. See this post for something similar:

https://www.elegantbi.com/post/bestpracticerulesavings
________________________________
