### ISSUE TITLE
Adding a zoom feature.

### ISSUE THREAD

**Issue by mbbau** [m-kovalsky/ReportAnalyzer#9]
**Is your feature request related to a problem? Please describe.**
This is my first time using the application, as shown in the video of (Havens Consulting)[https://www.youtube.com/watch?v=WT_5nOPdbqk] by Michael Kovalsky. My Report has personalized dimensions that are 1900 of width for 1000 of height. With this dimensions I can't see the hole page in te report analyzer but a fraction of it, and the slicer on the rigth only allows me to go down or up, but not left or rigth.

**Describe the solution you'd like**
I would love to have a kind of zoom command in the panel, in order to zoom out and be able to see the hole report.

**Describe alternatives you've considered**
Alternatively, report analyzer could have a scroll bar to allow me to scroll from rigth to left in my report.

**Additional context**
I will send you a screenshot of my issue for you to see. If there is a scroll bar or a way to work this around, please forgive me for this message as I wasn't able to find it. Thanks for yout amazing application.

I am not allow to share my pbi file as it contains clients data.

![image](https://user-images.githubusercontent.com/61053776/171707739-db1f8dd0-3fdd-4182-8be6-458ce89261e8.png)

**Comment by m-kovalsky** [comment]
As stated in the comment in your other issue, there is a scroll bar (vertical & horizontal) for wide/tall reports.

**Comment by mbbau** [comment]
Thank you very much for your response. Your tool is amazing.
